name: ci

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ "22.x" ]

    steps:
      - uses: actions/checkout@v4
      # pnpm/action-setup@v2 automatically installs version defined in `package.json`
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: mv dist/index.js docs/index.js
      - name: Upload build-artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            docs/

  trigger-deploy:
    needs: build
    uses: SzymonMakula/sigma-cropper/.github/workflows/deploy.yml@main